fullnameOverride: argocd
dex: {enabled: false}
notifications: {enabled: false}
applicationSet:
  replicas: 0
configs:
  params:
    server.insecure: true
    controller.status.processors: '5'
    controller.operation.processors: '3'
  cm:
    timeout.reconciliation: 60s
    resource.customizations.health.argoproj.io_Application: |
      hs = {status = "Progressing", message = "Waiting for child application"}
      if obj.status ~= nil and obj.status.health ~= nil then
        hs.status = obj.status.health.status
        hs.message = obj.status.health.message
      end
      return hs
server:
  resources:
    requests: {cpu: 50m, memory: 64Mi}
    limits: {cpu: 500m, memory: 256Mi}
controller:
  resources:
    requests: {cpu: 100m, memory: 256Mi}
    limits: {cpu: '1', memory: 768Mi}
repoServer:
  resources:
    requests: {cpu: 100m, memory: 128Mi}
    limits: {cpu: '1', memory: 512Mi}
redis:
  resources:
    requests: {cpu: 25m, memory: 32Mi}
    limits: {cpu: 250m, memory: 128Mi}
