apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespaces.yaml
- postgres.yaml
- workloads.yaml
- ingress.yaml
- policies.yaml
- monitoring.yaml
- analysis.yaml
- dashboard.yaml
images:
- name: ticket-backend
  newName: ghcr.io/wmcbay13/ticket-platform-backend
  digest: sha256:5664092b829eca467acc8b1f5096317373b9c206df545334b7efe601cd324edd
- name: ticket-web
  newName: ghcr.io/wmcbay13/ticket-platform-web
  digest: sha256:c7d84474581e1372d121bf01810a1d5b2d4059285b90e7a2b0a9a4fb076755fc
