kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
nodes:
  - role: control-plane
  - role: worker
    labels:
      ticket-platform/storage: postgres
    extraMounts:
      - hostPath: DATA_DIRECTORY
        containerPath: /var/local/ticket-platform
  - role: worker
