import React, { useEffect, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { money, request, reserve, type Event, type Order, type Scenario } from './api'
import './style.css'

const eventStyle:Record<string,{category:string;color:string;symbol:string}> = {
  'neon-nights':{category:'MUSIC',color:'purple',symbol:'◍'},
  'cloud-native-live':{category:'TECH & COMMUNITY',color:'green',symbol:'⌘'},
  'rooftop-sessions':{category:'LIVE SESSIONS',color:'orange',symbol:'☀'},
}
function App(){
  const [events,setEvents]=useState<Event[]>([]),[selected,setSelected]=useState<Event|null>(null),[order,setOrder]=useState<Order|null>(null)
  const [quantity,setQuantity]=useState(1),[scenario,setScenario]=useState<Scenario>('success'),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[pollError,setPollError]=useState('')
  const key=useRef(crypto.randomUUID())
  async function loadEvents(){setLoading(true);try{setEvents(await request<Event[]>('/api/events'));setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
  useEffect(()=>{void loadEvents();const id=new URLSearchParams(location.search).get('order');if(id)request<Order>(`/api/orders/${encodeURIComponent(id)}`).then(setOrder).catch(e=>setError(e.message))},[])
  useEffect(()=>{
    if(!order||order.status!=='pending')return
    const abort=new AbortController()
    const timer=setInterval(()=>{request<Order>(`/api/orders/${order.id}`,{signal:abort.signal}).then(o=>{setOrder(o);setPollError('');if(o.status!=='pending')void loadEvents()}).catch(e=>{if(!abort.signal.aborted)setPollError(`Reconnecting… ${e.message}`)})},1000)
    return()=>{clearInterval(timer);abort.abort()}
  },[order?.id,order?.status])
  function choose(event:Event){setSelected(event);setQuantity(1);setScenario('success');key.current=crypto.randomUUID();setError('')}
  async function book(){if(!selected||busy)return;setBusy(true);setError('');try{const o=await reserve(selected,quantity,scenario,key.current);setOrder(o);setSelected(null);history.replaceState({},'',`?order=${o.id}`)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  function closeOrder(){setOrder(null);setPollError('');history.replaceState({},'',location.pathname);void loadEvents()}
  return <div className="app">
    <header><a className="brand" href="/" aria-label="Gather home"><span className="brand-icon">g.</span>gather<span className="brand-dot">.</span></a><nav><a href="#events">Discover events</a><span className="demo-badge"><i/>Live demo</span></nav></header>
    <main>
      <section className="hero"><div><span className="eyebrow"><span/>GOOD TIMES START HERE</span><h1>Be there.<br/><span>Make a memory.</span></h1><p>From late-night sets to big ideas. Discover what’s happening, find your people, and save your spot.</p><a className="primary-link" href="#events">Find your next experience <span>↗</span></a><div className="hero-note"><span className="avatars">◉ ◉ ◉</span><span>Music. Community. A little spontaneity.</span></div></div><div className="hero-art" aria-hidden="true"><div className="orbit o1"/><div className="orbit o2"/><div className="art-star">✳</div><div className="floating-ticket"><span>YOUR NEXT<br/>GREAT NIGHT</span><b>ADMIT ONE</b><div className="barcode"/><small>MAKE IT A MEMORY ↗</small></div><span className="art-caption">LESS SCROLLING.<br/>MORE SHOWING UP.</span></div></section>
      <section id="events" className="events"><div className="section-title"><div><span className="eyebrow">ON THE CALENDAR</span><h2>Something to look forward to.</h2></div><span className="count">{events.length} upcoming events</span></div>
        {error&&!selected&&<div role="alert" className="error">{error} <button onClick={()=>void loadEvents()}>Retry</button></div>}
        {loading&&events.length===0?<p className="loading">Finding your next experience…</p>:<div className="event-grid">{events.map(event=>{const visual=eventStyle[event.id]??eventStyle['neon-nights'];const date=new Date(event.starts_at);return <article className="event-card" key={event.id}><div className={`event-image ${visual.color}`}><span className="category">{visual.category}</span><span className="event-symbol" aria-hidden="true">{visual.symbol}</span><div className="date-chip"><b>{date.getDate()}</b><span>{date.toLocaleDateString('en-US',{month:'short'})}</span></div><span className="image-caption">GATHER / LIVE</span></div><div className="event-body"><div className="event-meta"><span>{date.toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'})} · {date.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})}</span></div><h3>{event.title}</h3><p className="venue">⌖ {event.venue}</p><p className="description">{event.description}</p><div className="card-bottom"><span><b>{money(event.price_cents)}</b><small> / ticket</small></span><button onClick={()=>choose(event)} disabled={event.available===0}>{event.available===0?'Sold out':'Get tickets'} <span>↗</span></button></div><span className="availability"><i/>{event.available.toLocaleString()} spots available</span></div></article>})}</div>}
      </section>
      <section className="how-it-works"><span className="eyebrow">A SMALL APP. A BIGGER STORY.</span><h2>Your spot, in three steps.</h2><div className="steps"><div><b>01</b><h3>Find your thing</h3><p>Browse the calendar and pick an experience.</p></div><div><b>02</b><h3>Save your spot</h3><p>Choose your tickets. Your reservation starts instantly.</p></div><div><b>03</b><h3>You’re on the list</h3><p>Watch your order move from pending to confirmed.</p></div></div></section>
    </main><footer><span className="brand">gather.</span><p>A ticket-booking demo. Payments are simulated; no money is charged.</p><a href="https://github.com/wmcbay13/ticket-platform" target="_blank" rel="noreferrer">View the project ↗</a></footer>
    {selected&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="reserve-title"><button className="close" aria-label="Close reservation" onClick={()=>{if(!busy)setSelected(null)}}>×</button><span className="eyebrow">SAVE YOUR SPOT</span><h2 id="reserve-title">{selected.title}</h2><p>{selected.venue}</p><label htmlFor="quantity">Tickets</label><select id="quantity" value={quantity} disabled={busy} onChange={e=>{setQuantity(Number(e.target.value));key.current=crypto.randomUUID()}}>{Array.from({length:Math.min(10,selected.available)},(_,i)=><option key={i+1} value={i+1}>{i+1} {i===0?'ticket':'tickets'}</option>)}</select><label htmlFor="scenario">Simulated payment</label><select id="scenario" value={scenario} disabled={busy} onChange={e=>{setScenario(e.target.value as Scenario);key.current=crypto.randomUUID()}}><option value="success">Success</option><option value="decline">Declined payment</option><option value="retry">Retry, then success</option></select><div className="total"><span>Total</span><b>{money(quantity*selected.price_cents)}</b></div><p className="simulation-note">Demo only. No card details or real payment required.</p>{error&&<p className="error" role="alert">{error}</p>}<button className="primary-button" onClick={()=>void book()} disabled={busy||selected.available===0}>{busy?'Reserving…':'Reserve tickets ↗'}</button></section></div>}
    {order&&<div className="modal-backdrop"><section className="modal order-modal" role="dialog" aria-modal="true" aria-labelledby="order-title"><button className="close" onClick={closeOrder} aria-label="Close order">×</button><div className={`status-icon ${order.status}`}>{order.status==='confirmed'?'✓':order.status==='failed'?'×':'◌'}</div><span className="eyebrow">YOUR RESERVATION</span><h2 id="order-title">{order.status==='confirmed'?'You’re on the list.':order.status==='failed'?'Payment didn’t go through.':'Saving your spot…'}</h2><p>{order.status==='pending'?'Your tickets are reserved while we simulate your payment.':order.status==='confirmed'?'Your payment is confirmed. Good times ahead.':'Your tickets have been released. You can try again.'}</p><div className="order-details"><span>{events.find(e=>e.id===order.event_id)?.title??order.event_id}</span><b>{order.quantity} {order.quantity===1?'ticket':'tickets'} · {money(order.total_cents)}</b></div><ol className="timeline"><li className="done"><span>✓</span>Reservation created</li><li className={order.status==='pending'?'active':'done'}><span>{order.status==='pending'?'◌':'✓'}</span>Simulated payment</li><li className={order.status==='confirmed'?'done':order.status==='failed'?'failed':''}><span>{order.status==='confirmed'?'✓':order.status==='failed'?'×':'3'}</span>{order.status==='failed'?'Order failed':'Order confirmed'}</li></ol><p aria-live="polite" className="status-label">Status: <b>{order.status}</b></p>{pollError&&<p role="status" className="error">{pollError}</p>}<small className="order-id">Order {order.id}</small><button className="primary-button" onClick={closeOrder}>Back to events ↗</button></section></div>}
  </div>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
